### ISSUE TITLE
Invalid Date on TypeCast for execute after 3.9.x

### ISSUE THREAD

**Issue by wellwelwel** [wellwelwel/sequelize#1]
## Traces

- Issue:  https://github.com/sequelize/sequelize/issues/17141
- Issue:  https://github.com/sequelize/sequelize/issues/17116
- Branch: https://github.com/sequelize/sequelize/tree/ephys/17141
- Commit: https://github.com/sequelize/sequelize/compare/main...ephys/17141

## Challenges from MySQL2 side

- [ ] Understand `DATETIME` behaviors when returned from `query` and `execute`
- [ ] Analyze how `execute` returns a `DATETIME` value in **MySQL2** `3.5.2`
- [ ] Analyze how `execute` returns a `DATETIME` value in **MySQL2** `3.9.2`
- [ ] Reproduce a minimal error case
- [ ] Fix it 🚀

## Steps for Sequelize

- [ ] Reproduce both success and failure cases (old / new versions from **MySQL2**)
- [ ] Test the solution on **Sequelize** in practice before to merge it

**Comment by max-zu** [comment]
Any progress on this ? We need to update mysql2 package due to [this](https://github.com/sidorares/node-mysql2/pull/2608) security update. But we can't due to this bug https://github.com/sequelize/sequelize/issues/17141

**Comment by wellwelwel** [comment]
Adressed to https://github.com/sidorares/node-mysql2/pull/2820.
